# MySQL
spring.application.name=NonConformity
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## AWS S3
aws.accessKeyId=${ACCESS_KEY_S3}
aws.secretKey=${SECRET_KEY_S3}
aws.region=${REGION_S3}
aws.s3.bucket=${NAME_BUCKET}
aws.s3.storage.max-file-size=${FILE_SIZE}

## SPRING FILE_SIZE
spring.servlet.multipart.max-file-size=${FILE_SIZE}
spring.servlet.multipart.max-request-size=${FILE_SIZE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## JPA / Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.depend-on-database-initialization=false

api.security.token.secret=${JWT_SECRET}